development:
  secret_key_base:              <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key:         <%= ENV["T_CONSUMER_KEY"] %>
  twitter_consumer_secret:      <%= ENV["T_CONSUMER_SECRET"] %>
  twitter_access_token:         <%= ENV["T_ACCESS_TOKEN"] %>
  twitter_access_token_secret:  <%= ENV["T_ACCESS_TOKEN_SECRET"] %>

test:
  secret_key_base:              <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key:         <%= ENV["T_CONSUMER_KEY"] %>
  twitter_consumer_secret:      <%= ENV["T_CONSUMER_SECRET"] %>
  twitter_access_token:         <%= ENV["T_ACCESS_TOKEN"] %>
  twitter_access_token_secret:  <%= ENV["T_ACCESS_TOKEN_SECRET"] %>

production:
  secret_key_base:              <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key:         <%= ENV["T_CONSUMER_KEY"] %>
  twitter_consumer_secret:      <%= ENV["T_CONSUMER_SECRET"] %>
  twitter_access_token:         <%= ENV["T_ACCESS_TOKEN"] %>
  twitter_access_token_secret:  <%= ENV["T_ACCESS_TOKEN_SECRET"] %>

